# expand.grid source file

Dim <- expand.grid(dim = c(10, 20),
                      dependency = dependency,
                      subspaceslist = list(c(1:3)),
                      marginslist = list(c(0.9)),
                      n = 10000,
                      prop = 0.05,
                      proptype = "proportional",
                      verbose = FALSE,
                      method = "Construction")
Sub <- expand.grid(dim = c(10),
                      dependency = dependency,
                      subspaceslist = list(c(1:2), c(1:3), c(1:5)),
                      marginslist = list(c(0.9)),
                      n = 10000,
                      prop = 0.05,
                      proptype = "proportional",
                      verbose = FALSE,
                      method = "Construction")
Mar <- expand.grid(dim = c(10),
                   dependency = dependency,
                   subspaceslist = list(c(1:3)),
                   marginslist = list(c(0.1), c(0.5), c(0.9)),
                   n = 10000,
                   prop = 0.05,
                   proptype = "proportional",
                   verbose = FALSE,
                   method = "Construction")
Num <- expand.grid(dim = c(10),
                   dependency = dependency,
                   subspaceslist = list(c(1:3)),
                   marginslist = list(c(0.9)),
                   n = c(1000, 5000, 10000),
                   prop = 0.05,
                   proptype = "proportional",
                   verbose = FALSE,
                   method = "Construction")
Prop <- expand.grid(dim = c(10),
                   dependency = dependency,
                   subspaceslist = list(c(1:3)),
                   marginslist = list(c(0.9)),
                   n = 10000,
                   prop = c(0.01, 0.05, 0.1),
                   proptype = "proportional",
                   verbose = FALSE,
                   method = "Construction")
Proptype <- expand.grid(dim = c(10),
                   dependency = dependency,
                   subspaceslist = list(c(1:3)),
                   marginslist = list(c(0.9)),
                   n = 10000,
                   prop = 0.05,
                   proptype = c("absolute", "proportional"),
                   verbose = FALSE,
                   method = "Construction")
Method <- expand.grid(dim = c(10),
                   dependency = dependency,
                   subspaceslist = list(c(1:3)),
                   marginslist = list(c(0.9)),
                   n = 10000,
                   prop = 0.05,
                   proptype = "proportional",
                   verbose = FALSE,
                   method = c("Rejection", "Construction"))

res <- rbind(Dim, Sub, Mar, Num, Prop, Proptype, Method)
rm(Dim, Sub, Mar, Num, Prop, Proptype, Method)
res